// ng-todo-app/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'NG Todos App';
  // angular is state management framework
  // state set for todos
  todos: string[] = [];
  todoTitle = '';

// angular app life cycle management
ngOnInit(){

}

  // add todo function
  addTodo(){
    this.todos.push(this.todoTitle);
    // using local storage
    localStorage.setItem('todos', JSON.stringify(this.todos));
  }
}

<link rel="stylesheet" href="app.component.css" />

<h1>{{title}}</h1>
<hr>
<ul>
  <li *ngFor="let todo of todos">
    {{todo}}
  </li>
</ul>
<hr>
<form (ngSubmit)="addTodo()">
  <input name="todoTitle" [(ngModel)]="todoTitle">
<input type="submit" value="Add Todo">
</form>

// react-todo-app/src/App.js
import logo from './logo.svg';
import './App.css';
import { useEffect, useRef, useState } from 'react';

function App() {

  // title binding
  const todoTitle = useRef();

  // apply life cycle hook
  useEffect(() => {
    const availableTodos = localStorage.getItem('todos');
    setTodos(availableTodos ? JSON.parse(availableTodos) : []);

  }, []);


  // add todo function
  function addTodo(event) {
    event.preventDefault();
    const next = [...todos, todoTitle.current.value];
    setTodos(next);
    localStorage.setItem('todos', JSON.stringify(next));
  }

  // react is state management 
  // framework
  // state of todos and update function
  const [todos, setTodos] = useState([]);
  return (
    <div>
      <ul>
        {todos.map(todo => (
          <li key={todo}>{todo}</li>
        ))}
      </ul>
      <form onSubmit={addTodo}>
        <input ref={todoTitle} />
        <input type="submit" value="Add Todo" />
      </form>
    </div>
  )

}

export default App;
