// vue-todo-app/src/components/TodoApp.vue
<template>
  <div class="hello">
    <h1>{{ msg }}</h1>
    <hr>
    <ul>
      <li v-for="todo in todos" :key="todo">{{ todo }}</li>
    </ul>
    <hr>
    <form v-on:submit.prevent="addTodo">
      <input v-model="todoTitle">
      <input type="submit" value="Add Todo">
    </form>
  </div>
</template>

<script>
export default {
  name: 'TodoApp',
  props: {
    msg: String
  },
  data: function () {
    return {
      todos: [],
      todoTitle: '',
    };
  },
  methods: {
    addTodo: function () {
      this.todos = [...this.todos, this.todoTitle];
      localStorage.setItem('todos', JSON.stringify(this.todos));
    }
  },
  mounted: function () {
    const availableTodos = JSON.parse(localStorage.getItem('todos'));
    this.todos = availableTodos || [];
  }
};
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
h3 {
  margin: 40px 0 0;
}

ul {
  list-style-type: none;
  padding: 0rem;
  margin-left: 13em;
}

li {
  padding: .5rem;
  text-align: left;
}



a {
  color: #42b983;
}
</style>

// svelte-todo-app/src/lib/TodoApp.svelte
<script>
    import { onMount } from "svelte";
    
    let todos = [];
    let todoTitle = "";

    function addTodo() {
        todos = [...todos, todoTitle];
        localStorage.setItem("todos", JSON.stringify(todos));
    }

    onMount(() => {
        const availableTodos = JSON.parse(localStorage.getItem("todos"));
        todos = availableTodos || [];
    });
</script>

<div>
    <h1>Svelte Todo App</h1>
    <hr />
    <ul>
        {#each todos as todo}
             <li>{todo}</li>
        {/each}
    </ul>
    <hr />
    <form on:submit|preventDefault={addTodo}>
        <input type="text" bind:value={todoTitle} />
        <input type="submit" value="Add Todo" />
    </form>
</div>

<style>
    input[type="submit"] {
        padding: 0.33rem;
        border: 1px solid magenta;
        border-radius: 3px;
    }
</style>
